auth_enabled: false

limits_config:
  allow_structured_metadata: true
  volume_enabled: true
  ingestion_rate_mb: 10240
  ingestion_burst_size_mb: 10240

server:
  http_listen_port: 3100
  grpc_server_max_recv_msg_size: 104857600 # 100 MB, might be too much, be careful
  grpc_server_max_send_msg_size: 104857600 # 100 MB, might be too much, be careful

common:
  ring:
    instance_addr: 0.0.0.0
    kvstore:
      store: inmemory
  replication_factor: 1
  path_prefix: /tmp/loki

schema_config:
  configs:
    - from: 2020-05-15
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h

storage_config:
  tsdb_shipper:
    active_index_directory: /tmp/loki/index
    cache_location: /tmp/loki/index_cache
  filesystem:
    directory: /tmp/loki/chunks

pattern_ingester:
  enabled: true

analytics:
  reporting_enabled: false
