server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: 'http://{{.LokiHost}}:{{.LokiPort}}/loki/api/v1/push'

scrape_configs:
  {{range .Instances}}
  - job_name: '{{.InstanceName}}'
    static_configs:
      - targets:
          - 'localhost'
        labels:
          job: '{{.InstanceName}}-postgres'
          __path__: '{{.PgLogLocation}}'
    {{end}}