global:
  scrape_interval: 10s

scrape_configs:
  {{range .Instances}}
  - job_name: '{{.InstanceName}}'
    metrics_path: '/probe?target={{.Hostname}}:{{.Port}}&auth_module={{.ClusterName}}'
    static_configs:
      - targets: [ '{{.ExporterHostname}}:{{.ExporterPort}}' ]
        labels:
          instance_name: '{{.InstanceName}}'
          cluster_name: '{{.ClusterName}}'
  - job_name: 'patroni-{{.InstanceName}}'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['{{.Hostname}}:{{.PatroniPort}}']
        labels:
          instance_name: '{{.InstanceName}}'
          cluster_name: '{{.ClusterName}}'
  {{end}}