apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app.kubernetes.io/component: exporter
    app.kubernetes.io/name: node-exporter
  name: node-exporter
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: exporter
      app.kubernetes.io/name: node-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/component: exporter
        app.kubernetes.io/name: node-exporter
    spec:
      containers:
        - args:
            - --path.sysfs=/host/sys
            - --path.rootfs=/host/root
            - --no-collector.wifi
            - --no-collector.hwmon
            - --collector.filesystem.ignored-mount-points=^/(dev|proc|sys|var/lib/docker/.+|var/lib/kubelet/pods/.+)($|/)
            - --collector.netclass.ignored-devices=^(veth.*)$
          name: node-exporter
          image: prom/node-exporter
          ports:
            - containerPort: 9100
              protocol: TCP
          resources:
            limits:
              cpu: 250m
              memory: 180Mi
            requests:
              cpu: 102m
              memory: 180Mi
          volumeMounts:
            - mountPath: /host/sys
              mountPropagation: HostToContainer
              name: sys
              readOnly: true
            - mountPath: /host/root
              mountPropagation: HostToContainer
              name: root
              readOnly: true
      volumes:
        - hostPath:
            path: /sys
          name: sys
        - hostPath:
            path: /
          name: root
---
kind: Service
apiVersion: v1
metadata:
  name: node-exporter
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port:   '9100'
spec:
  selector:
    app.kubernetes.io/component: exporter
    app.kubernetes.io/name: node-exporter
  ports:
    - name: node-exporter
      protocol: TCP
      port: 9100
      targetPort: 9100
---
kind: Pod
apiVersion: v1
metadata:
  name: node-exporter-vmagent
spec:
  volumes:
    - name: prometheus-config
      configMap:
        name: node-exporter-vmagent-configmap
        items:
          - key: prometheus.yml
            path: prometheus.yml
  containers:
    - name: node-exporter-vmagent
      image: victoriametrics/vmagent:latest
      volumeMounts:
        - mountPath: /etc/prometheus
          name: prometheus-config
      args:
        - "--promscrape.config=/etc/prometheus/prometheus.yml"
        - "--remoteWrite.url=http://borealis-service:8428/api/v1/write"
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: node-exporter-vmagent-configmap
data:
  prometheus.yml: |-
    global:
        scrape_interval: 10s
    scrape_configs:
      - job_name: 'node_exporter'
        metrics_path: '/metrics'
        static_configs:
          - targets: [ 'node-exporter:9100' ]