{
 "title": "Borealis cluster insights",
 "tags": [
  "Insights",
  "Basic",
  "Borealis"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "cluster", "label": "Cluster name", "query": "label_values(cluster_name)" },
   { "name": "instance_name", "label": "Instance name", "query": { "query": "label_values(instance_name)" } },
   { "name": "database", "label": "Database", "query": "label_values(datname)" },
   { "name": "interval", "label": "interval", "query": "1s,5s,1m,5m,1h,6h,1d" }
  ]
 },
 "panels": [
  {
   "title": "$cluster - Status",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "targets": [
    {
     "expr": "patroni_postgres_running{cluster_name=~\"[[cluster]]\"}"
    },
    {
     "expr": "patroni_replica{cluster_name=~\"[[cluster]]\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "ceil((time() - patroni_postmaster_start_time{cluster_name=~\"[[cluster]]\"}) / 60)"
    }
   ]
  },
  { "title": "$cluster - Main metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "$cluster - Connections",
   "type": "timeseries",
   "gridPos": { "x": 8, "y": 0, "w": 8, "h": 10 },
   "targets": [
    {
     "legendFormat": "__auto",
     "expr": "avg by (state) (sum(max_over_time(pg_stat_activity_count{cluster_name=~\"[[cluster]]\"}[5m]) or\nmax_over_time(pg_stat_activity_count{cluster_name=~\"[[cluster]]\"}[5m])) by (state))"
    },
    {
     "expr": "max(pg_settings_max_connections{cluster_name=~\"[[cluster]]\"})"
    }
   ]
  },
  {
   "title": "$cluster - Transactions per second",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pg_stat_database_xact_commit{cluster_name=~\"[[cluster]]\"}[$interval])) or \nsum(irate(pg_stat_database_xact_commit{cluster_name=~\"[[cluster]]\"}[5m]))",
     "legendFormat": "Commits"
    },
    {
     "expr": "sum(rate(pg_stat_database_xact_rollback{cluster_name=~\"[[cluster]]\"}[$interval])) or\nsum(irate(pg_stat_database_xact_rollback{cluster_name=~\"[[cluster]]\"}[5m]))",
     "legendFormat": "Rollbacks"
    }
   ]
  },
  {
   "title": "$cluster - Active Connections by instance",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 0 },
   "repeat": "service_name",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max by (instance_name)(pg_stat_activity_count{cluster_name=~\"[[cluster]]\",state='active'})",
     "legendFormat": "{{instance_name}}"
    },
    {
     "expr": "avg by (cluster_name) (max_over_time(pg_settings_max_connections{cluster_name=~\"[[cluster]]\"}[$interval]) or \nmax_over_time(pg_settings_max_connections{cluster_name=~\"[[cluster]]\"}[5m]))",
     "legendFormat": "Maximum connections"
    }
   ]
  },
  {
   "title": "$cluster - Latency",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by (service_name,state) (max_over_time(pg_stat_activity_max_tx_duration{cluster_name=~\"[[cluster]]\"}[$interval]) or\nmax_over_time(pg_stat_activity_max_tx_duration{cluster_name=~\"[[cluster]]\"}[5m]))",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "$cluster - Replica Lag",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "pg_replication_lag{cluster_name=\"[[cluster]]\"}",
     "legendFormat": "Replica: {{instance_name}}"
    }
   ]
  },
  {
   "title": "$cluster - Transactions count (ID wraparound)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max by (datname) (pg_database_datfrozenxid_age_datfrozenxid{cluster_name=~\"[[cluster]]\",datname !~ \"template.*\"})",
     "legendFormat": "{{datname}} Transaction Ids"
    },
    {
     "expr": "max by (datname) (pg_database_datfrozenxid_age_datminmxid{cluster_name=~\"[[cluster]]\",datname !~ \"template.*\"})",
     "legendFormat": "{{datname}} Multi-transaction Ids"
    }
   ]
  },
  {
   "title": "$cluster - Count of WALs waiting to be archived",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 26, "w": 8, "h": 10 },
   "targets": [
    {
     "expr": "pg_archiver_pending_wal_count{cluster_name=~\"[[cluster]]\"}",
     "legendFormat": "WAL pending for: {{instance_name}}"
    }
   ]
  },
  {
   "title": "$cluster -  Bytes in replication slots",
   "type": "timeseries",
   "gridPos": { "x": 8, "y": 26, "w": 8, "h": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "pg_replication_slots_restart_lsn_bytes{cluster_name=~\"[[cluster]]\"}",
     "legendFormat": "Slot name: {{slot_name}} - Slot type: {{slot_type}}"
    }
   ]
  },
  {
   "title": "$cluster  - Replication slots",
   "type": "table",
   "gridPos": { "x": 16, "y": 26, "w": 8, "h": 10 },
   "targets": [
    {
     "expr": "pg_replication_slots_active{cluster_name=~\"[[cluster]]\"}"
    }
   ]
  },
  {
   "title": "$cluster - Locks",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 36, "w": 8, "h": 10 },
   "targets": [
    {
     "expr": "avg by (cluster_name,datname) (max_over_time(pg_locks_count{cluster_name=~\"[[cluster]]\",datname!~\"template.*\"}[5m]) or\nmax_over_time(pg_locks_count{cluster_name=~\"[[cluster]]\",datname!~\"template.*\"}[5m]))",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "$cluster - Deadlocks and Conflicts",
   "type": "timeseries",
   "gridPos": { "x": 8, "y": 36, "w": 8, "h": 10 },
   "targets": [
    {
     "alias": "conflicts",
     "expr": "sum(rate(pg_stat_database_deadlocks{cluster_name=~\"[[cluster]]\"}[5m])) or \nsum(irate(pg_stat_database_deadlocks{cluster_name=~\"[[cluster]]\"}[5m]))",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "conflicts" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "node_name", "operator": "=~", "value": "/^$node_name$/" }
     ],
     "legendFormat": "Deadlocks"
    },
    {
     "alias": "deadlocks",
     "expr": "sum(rate(pg_stat_database_conflicts{cluster_name=~\"[[cluster]]\"}[5m])) or \nsum(irate(pg_stat_database_conflicts{cluster_name=~\"[[cluster]]\"}[5m]))",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "deadlocks" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "node_name", "operator": "=~", "value": "/^$node_name$/" }
     ],
     "legendFormat": "Conflicts"
    }
   ]
  },
  { "title": "OS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "Disk Read/Write latency",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 54, "w": 8, "h": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(node_disk_read_time_seconds_total{device=~\"nvme0n1\"}[5m]) / rate(node_disk_reads_completed_total{device=~\"nvme0n1\"}[5m])",
     "legendFormat": "Read"
    },
    {
     "expr": "rate(node_disk_write_time_seconds_total{device=~\"nvme0n1\"}[5m]) / rate(node_disk_writes_completed_total{device=~\"nvme0n1\"}[5m])",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "Disk Read/Write IOPs",
   "type": "timeseries",
   "gridPos": { "x": 8, "y": 54, "w": 8, "h": 10 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "avg by (node_name) (sum(\n(rate(node_disk_reads_completed_total{device=~\"nvme0n1\", node_name=\"\"}[10s]) or \nirate(node_disk_reads_completed_total{device=~\"nvme0n1\", node_name=\"\"}[5m]))\n))",
     "legendFormat": "Reads"
    },
    {
     "expr": "avg by (node_name) (sum(\n(rate(node_disk_writes_completed_total{device=~\"nvme0n1\", node_name=\"\"}[10s]) or \nirate(node_disk_writes_completed_total{device=~\"nvme0n1\", node_name=\"\"}[5m]))\n))",
     "legendFormat": "Writes"
    }
   ]
  },
  {
   "title": "Disk used space",
   "type": "stat",
   "gridPos": { "x": 16, "y": 47, "w": 8, "h": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{mountpoint=\"/\",fstype!=\"rootfs\"})"
    }
   ]
  },
  {
   "title": "Swap I/O",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "avg by (node_name) (rate(node_vmstat_pswpin{}[$interval]) * 4096 or irate(node_vmstat_pswpin{}[5m]) * 4096)",
     "legendFormat": "Swap In (Reads)"
    },
    {
     "expr": "avg by (node_name) (rate(node_vmstat_pswpout{}[$interval]) * 4096 or irate(node_vmstat_pswpout{}[5m]) * 4096)",
     "legendFormat": "Swap Out (Writes)"
    },
    {
     "expr": "avg by (node_name) ((rate(node_vmstat_pswpin{}[$interval]) * 4096 or \nirate(node_vmstat_pswpin{}[5m]) * 4096) + \n(rate(node_vmstat_pswpout{}[$interval]) * 4096 or \nirate(node_vmstat_pswpout{}[5m]) * 4096))",
     "legendFormat": "Total"
    }
   ]
  }
 ]
}