apiVersion: 1

datasources:
  - name: Metrics
    type: prometheus
    access: proxy
    url: http://{{.PrometheusHost}}:{{.PrometheusPort}}
    isDefault: true
  - name: ClickHouse
    type: grafana-clickhouse-datasource
    jsonData:
      port: {{.ClickhousePort}}
      server: {{.ClickhouseHost}}
      tlsSkipVerify: {{.ClickhouseTlsSkipVerify}}
  - name: Loki
    type: loki
    access: proxy
    url: http://{{.LokiHost}}:{{.LokiPort}}
